// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using behsoftbolao.api.Data;

#nullable disable

namespace behsoftbolao.api.Migrations
{
    [DbContext(typeof(BolaoDbContext))]
    [Migration("20240618172434_add_table_images")]
    partial class add_table_images
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Bolao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampeonatoAnualId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Updated")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoAnualId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UX_codigo_bolao");

                    b.HasIndex("DonoId");

                    b.ToTable("Boloes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36e9709a-c691-43b6-8767-5e81f876c5e6"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN000",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 0",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("2627d703-c504-4b94-ae8e-4d09490343af"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN001",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 1",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("df3c427d-a17e-4646-8568-7a978091814d"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN002",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 2",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("7bcd0722-0268-460e-8082-f3911b50f7e6"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN003",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 3",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("17038752-c57b-442b-a147-5d5fd539620f"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN004",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 4",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("00ad539e-1270-4024-ae43-618c857b1c84"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN005",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 5",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("6bdfcf52-3a94-4169-8090-2fdf8ab5209d"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN006",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 6",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("c8e7b33e-a529-4dfc-859d-c813bf838f86"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN007",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 7",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("9d6f7543-c0b8-4702-817a-3d3c29a2cee4"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN008",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 8",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("4553ea69-c009-4d04-8903-1df72148583f"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN009",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 9",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("eced80e0-3315-44b0-8a3a-ae274e296c08"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN010",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 10",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("a991e7f6-618f-433a-97d6-68c2ed5eb03e"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN011",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 11",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("05ffb1ae-3098-4292-bea8-5c304797f978"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN012",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 12",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("55c36ef4-dcd4-4334-ad52-09e71ea0a74d"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN013",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 13",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("8abdd214-8320-4b90-93a2-22c6c791a7e3"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN014",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 14",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("44a999e1-9b1f-49d4-99dc-f32fe573b2e5"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN015",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 15",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("951da53a-b0fe-473e-b6db-464ddeb40bb8"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN016",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 16",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("5576b040-83f5-47a0-a656-708748ddd36b"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN017",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 17",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("dc7b733c-72ba-4de7-9ea0-6a8693e007a2"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN018",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 18",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("6d74bece-4768-482c-9099-04fe30db1544"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN019",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 19",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("d0ad8522-195f-48aa-aa72-82348c4d0d25"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN020",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 20",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("eba3b82a-bd54-40d0-b22e-690c68af2ed8"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN021",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 21",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("4316c3b0-d02a-4892-a86c-f6159bdb85d2"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN022",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 22",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("fe6a1863-5b61-42d7-abc4-b1733806a9c0"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN023",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 23",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("21f66624-02c9-4231-9ff4-0681b4539a18"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN024",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 24",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("8f482d48-43f6-48b9-ba09-37591381906b"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN025",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 25",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("4670e6f2-b623-4ec8-be41-5257a0a2301b"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN026",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 26",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("1745ef08-b9b3-4fc8-b567-4da70d1d6f53"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN027",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 27",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("e2ec19c3-fcd2-4bc0-98cf-1133515d3724"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN028",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 28",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("4d5fa54c-62e3-496a-9d4a-d9b5d5d93cc5"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN029",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 29",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("b8ca08b9-8c15-4d69-b43e-ef4f78f3ad91"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN030",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 30",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("b4d6dee6-b2f5-49fa-b872-ff9cf6b79947"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN031",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 31",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("93f1fcaf-1cf0-4c88-be71-34b9e87a070e"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN032",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 32",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("0f1ff8b2-cb4f-47ba-b5a8-52b2aee6ed4d"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN033",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 33",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("d1ec4012-3223-48d2-aa58-24d7587fbf90"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN034",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 34",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("299fe09a-7790-4014-b87b-e3a63cf1c80a"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN035",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 35",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("441d30e2-d0a0-4c33-86da-93382ab96621"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN036",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 36",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("b7e493fe-8ade-45eb-ac8d-29395cf2951c"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN037",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 37",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("eaf6fff8-5860-4368-9e93-d81f8b5951b4"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN038",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 38",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("a451db38-3182-4f9b-8989-93ebc3a7d705"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN039",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 39",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("ace8a5e0-958c-44b1-b02f-550c034b9987"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN040",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 40",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("68c1e204-78ec-429a-ace4-6edd87e60031"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN041",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 41",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("c98101c2-5759-4f76-beaa-d41053ded26b"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN042",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 42",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("99d4c1cf-48cf-449d-8c98-3ef5492b33cc"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN043",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 43",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("8caeae22-e12e-439a-bacb-02c4a51711f3"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN044",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 44",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("781bd315-ef76-438a-9859-bcaa8f21cbdd"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN045",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 45",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("82a48848-29ff-4f64-9f77-fc835fdc0ca2"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN046",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 46",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("80e326bc-c88b-486b-a5c9-bfa9503c4a7c"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN047",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 47",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("3de6f0a7-219d-4e73-aabb-be24ea72c86b"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN048",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 48",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("4623b4d4-85c8-4e16-adf2-45758c7c2a7e"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN049",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 49",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("9f776d79-7c5d-4fe5-9ffa-398fc40af0e4"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN050",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 50",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("ac05c84d-a257-4882-9f81-ddc7ae0df1a2"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN051",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 51",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("bfc06fb6-1919-4484-b046-f62ddf179690"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN052",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 52",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("14d612f5-afe3-499c-a5a9-e65ccf343f2f"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN053",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 53",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("a4ba7d42-8207-4a00-8584-622403e00bb5"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN054",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 54",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("28faf52a-3647-4ac3-9b6c-7217c5826dd6"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN055",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 55",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("6ea93590-d8b3-4ede-9b4a-e4a8963930b1"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN056",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 56",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("884cf49d-1af7-4c60-b5d8-b7bf235601d7"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN057",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 57",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("0388ebd9-6a91-43ec-9ef4-e8713876b54c"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN058",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 58",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("857415f2-3411-454b-b993-d9756a3ba183"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN059",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 59",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("2e77640c-22a8-4406-9492-34d81d237c37"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN060",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 60",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("c9b4cd05-b66b-4893-8e10-ff39b0900175"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN061",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 61",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("1abba436-5dc7-4391-8c5b-5d0e5a2da0cc"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN062",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 62",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("ccea5603-0501-44ce-b117-938b884fb6c3"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN063",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 63",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("a514e294-7207-4f6f-86b0-ab87f4bae374"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN064",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 64",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("4a7e4e86-53c0-47ca-809f-a7ba546bc720"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN065",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 65",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("311ebcd3-eb9d-4426-836f-0ceccb06ef75"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN066",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 66",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("49019fad-5df0-4441-9fb7-ff1294581ef3"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN067",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 67",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("90b4fccd-c6e7-4b1b-a92e-9a386fb55484"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN068",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 68",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("3c9e7b95-2975-4e19-93fc-bd8e60ca8b3d"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN069",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 69",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("637c833d-f45b-4360-92fb-7693b144c82f"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN070",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 70",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("f4b29308-f0fb-44e8-92fc-8edfbb82d5af"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN071",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 71",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("8ed3548e-3de2-4300-ae4f-144718a14aba"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN072",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 72",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("12d9b894-6440-4b83-96d6-e94bc28a6999"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN073",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 73",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("55fbd585-a297-4216-9048-5bd57343afc0"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN074",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 74",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("8daf313d-71b0-42b1-a5f5-887ca5e98453"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN075",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 75",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("c49c15ab-2a23-4ea0-a198-16127f6f8c64"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN076",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 76",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("41920598-a1c5-4275-83b3-bbe4c4700124"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN077",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 77",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("86f26a9c-89f5-42fa-9cd6-02e7e5977c40"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN078",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 78",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("d7e3467f-3605-4b97-b301-034704eb9e7d"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN079",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 79",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("e1431594-0944-4437-a57c-3ccfbf8e5352"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN080",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 80",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("1e24b887-00ac-4af9-8b99-cdfe0719aa74"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN081",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 81",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("3da0e5cb-5281-42ea-8f7e-7c34c6de7502"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN082",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 82",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("8446a899-4c7f-4b62-ac92-ed5320aafe6a"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN083",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 83",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("6388be74-1bb9-4636-97e5-14e5e8d0e442"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN084",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 84",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("f0cf9dea-f303-44c8-b07e-25ec8e99604a"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN085",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 85",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("54d3b16f-6515-4962-a913-cac49384153d"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN086",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 86",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("1bd5780a-fb27-4100-994b-f78b2127f921"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN087",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 87",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("30d52d1c-3700-4bab-b059-7bfdc34c3ce9"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN088",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 88",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("a708c743-348a-4643-bc8f-961c93c64db4"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN089",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 89",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("03b8c00b-35d5-44a4-9c11-f61955a52b7e"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN090",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 90",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("8ca828ee-baa5-4d25-83c3-8457b0e8d635"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN091",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 91",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("85abe0dd-cdd3-400c-8044-e4f3d4d23be1"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN092",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 92",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("124a97f7-5d34-41af-ac30-bc2159e3b41e"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN093",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 93",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("2ae4949e-c4a9-48ae-b546-bad32c91492d"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN094",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 94",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("7a6319c5-f28a-4b00-ae90-35c69bf59b49"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN095",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 95",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("a3b2e75b-e473-415b-a276-887e0252d211"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN096",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 96",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("7189d6c7-565c-4aae-958a-7bf60f28ce12"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN097",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 97",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("ee434476-97c3-41c0-838a-d7c51948f295"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN098",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 98",
                            Updated = false
                        },
                        new
                        {
                            Id = new Guid("ab2ca290-ba70-46e4-8ebc-f8d5860c8011"),
                            CampeonatoAnualId = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Codigo = "BAN099",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DonoId = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            Titulo = "Bolão do Banese 2024 - 99",
                            Updated = false
                        });
                });

            modelBuilder.Entity("Core.Models.CampeonatoAnual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId", "Ano")
                        .IsUnique();

                    b.ToTable("CampeonatoAnual");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70eb28a3-833f-4a63-8d6f-b1dcf9660111"),
                            Ano = 2026,
                            CampeonatoId = new Guid("9dc2938e-c245-43a2-bb8b-fe58f6c09a9d")
                        });
                });

            modelBuilder.Entity("Core.Models.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampeonatoAnualId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PlacarTimeDois")
                        .HasColumnType("integer");

                    b.Property<int?>("PlacarTimeUm")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TimeDoisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TimeUmId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoAnualId");

                    b.HasIndex("TimeDoisId");

                    b.HasIndex("TimeUmId");

                    b.ToTable("Jogo");
                });

            modelBuilder.Entity("Core.Models.Palpite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipanteID")
                        .HasColumnType("uuid");

                    b.Property<int?>("PontosTimeDois")
                        .HasColumnType("integer");

                    b.Property<int?>("PontosTimeUm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("ParticipanteID", "JogoId")
                        .IsUnique();

                    b.ToTable("Palpites");
                });

            modelBuilder.Entity("Core.Models.Participante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BolaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Pontuacao")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BolaoId");

                    b.HasIndex("UsuarioId", "BolaoId")
                        .IsUnique();

                    b.ToTable("Participante");
                });

            modelBuilder.Entity("Database.Models.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("Campeonato");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9dc2938e-c245-43a2-bb8b-fe58f6c09a9d"),
                            Nome = "Copa do Mundo",
                            Sigla = "FWC"
                        },
                        new
                        {
                            Id = new Guid("f28d4dc4-5198-41ce-b785-286d589ceca6"),
                            Nome = "Brasileirão - Série A",
                            Sigla = "BRA-A"
                        },
                        new
                        {
                            Id = new Guid("c9df5ae9-6c93-4f6c-ab09-a145faa599da"),
                            Nome = "Brasileirão - Série B",
                            Sigla = "BRA-B"
                        });
                });

            modelBuilder.Entity("Database.Models.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconeBandeira")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Time");
                });

            modelBuilder.Entity("Database.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = "29784a75-4721-4da4-b8b7-d167c588d5cf",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://ui-avatars.com/api/?background=random&name=Admin",
                            ConcurrencyStamp = "4ea03c43-4979-4c10-9a1a-6d4dfe1c5406",
                            CriadoEm = new DateTime(2024, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Nome = "Admin",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a6844db1-8c1e-400d-9913-7fd8f9059090",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("behsoftbolao.api.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileDescription")
                        .HasColumnType("text");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Core.Models.Bolao", b =>
                {
                    b.HasOne("Core.Models.CampeonatoAnual", "CampeonatoAnual")
                        .WithMany("Boloes")
                        .HasForeignKey("CampeonatoAnualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Usuario", "Dono")
                        .WithMany("Dono")
                        .HasForeignKey("DonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampeonatoAnual");

                    b.Navigation("Dono");
                });

            modelBuilder.Entity("Core.Models.CampeonatoAnual", b =>
                {
                    b.HasOne("Database.Models.Campeonato", "Campeonato")
                        .WithMany("CampeonatosAnuais")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("Core.Models.Jogo", b =>
                {
                    b.HasOne("Core.Models.CampeonatoAnual", "CampeonatoAnual")
                        .WithMany("Jogos")
                        .HasForeignKey("CampeonatoAnualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Time", "TimeDois")
                        .WithMany("TimesDois")
                        .HasForeignKey("TimeDoisId");

                    b.HasOne("Database.Models.Time", "TimeUm")
                        .WithMany("TimesUm")
                        .HasForeignKey("TimeUmId");

                    b.Navigation("CampeonatoAnual");

                    b.Navigation("TimeDois");

                    b.Navigation("TimeUm");
                });

            modelBuilder.Entity("Core.Models.Palpite", b =>
                {
                    b.HasOne("Core.Models.Jogo", "Jogo")
                        .WithMany("Plapites")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Participante", "Participante")
                        .WithMany("Palpites")
                        .HasForeignKey("ParticipanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Core.Models.Participante", b =>
                {
                    b.HasOne("Core.Models.Bolao", "Bolao")
                        .WithMany("Participantes")
                        .HasForeignKey("BolaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Usuario", "Usuario")
                        .WithMany("Participante")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Models.Bolao", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Core.Models.CampeonatoAnual", b =>
                {
                    b.Navigation("Boloes");

                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("Core.Models.Jogo", b =>
                {
                    b.Navigation("Plapites");
                });

            modelBuilder.Entity("Core.Models.Participante", b =>
                {
                    b.Navigation("Palpites");
                });

            modelBuilder.Entity("Database.Models.Campeonato", b =>
                {
                    b.Navigation("CampeonatosAnuais");
                });

            modelBuilder.Entity("Database.Models.Time", b =>
                {
                    b.Navigation("TimesDois");

                    b.Navigation("TimesUm");
                });

            modelBuilder.Entity("Database.Models.Usuario", b =>
                {
                    b.Navigation("Dono");

                    b.Navigation("Participante");
                });
#pragma warning restore 612, 618
        }
    }
}
